### ISSUE TITLE
Android OS NullPointerException 

### ISSUE THREAD

**Issue by andygup** [Esri/cordova-plugin-advanced-geolocation#26]
Problem: If you accidentally initialize the plugin twice in a row, it throws a native NullPointerException.

Solution: Need to protect against duplicate request failures in `onRequestPermissionResult ` where `grantResults[]` will be null.

```javascript
W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                           java.lang.NullPointerException: Attempt to read from field 'android.view.HardwareRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                                               at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:504)
                                                               at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1104)
                                                               at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:560)
                                                               at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by andygup** [comment]
Closed at https://github.com/Esri/cordova-plugin-advanced-geolocation/commit/6fe195a5faf25804ccfb4fe0708a8eb680e75139
